name: CI Testt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Python 3.9 Configurations
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name:  Dependency check
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pytest
      env:
        DATABASE_URL: "sqlite:///:memory:"
        SQLALCHEMY_WARN_20: "0"
      run: |
        pytest