# .github/workflows/ci.yml

name: CI de Testes da API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar Testes com Pytest
      env:
        DATABASE_URL: "sqlite:///:memory:"
        SQLALCHEMY_WARN_20: "0"
      run: |
        pytest